### ISSUE TITLE
no nodemanager overview

### ISSUE THREAD

**Issue by Mrchumo** [vqcuong/hadoop_exporter#3]
After import yarn.json in grafana, there is only the resourcemanager overview and no nodemanager overview，Can you provide the nodemanager dashboard, thanks

**Comment by vqcuong** [comment]
Hi @Mrchumo , sorry for late responding. I've just update new YARN dashboard with new charts for NodeManager, Spark Shuffle Service and Resource Queue Management.

**Comment by Mrchumo** [comment]
thank you for your help. Another problem is that the yarn dashboard has a metric named hadoop_ yarn_ resourcemanager_ state, but no data is displayed in the panel. I can't find this metric in Prometheus. I guess that the exporter didn't collect it. The yarn version is 3.1.3. The metric hadoop_ yarn_ resourcemanager_ queuemetrics, type=maxcapacity also has the same problem

**Comment by vqcuong** [comment]
@Mrchumo yeah, let me check this. It may be due to the difference between hadoop version. I mainly focus on version 3.3.x so let me check and update this for you.

**Comment by vqcuong** [comment]
Hi @Mrchumo, I found the problem, this hadoop_yarn_resourcemanager_state show the state of each resource manager. In HA (high available) clusters, this state consists of two values: active and standby while in non HA clusters, there is only one resource manager and it's state is always active, so there is no information in JMX to parse the state. If you are using non HA cluster, you can ignore this metrics. For hadoop_yarn_resourcemanager_queuemetrics metric, I've checked and still seen this metrics when testing with hadoop version 3.1.3

**Comment by Mrchumo** [comment]
i think my cluster is HA cluster, in the home page of the yarn(ip:8088), i see that **resourcemanager HA state: active**, **resourcemanager HA zookeeper connection state: connected**. Maybe I configured it incorrectly. In my configuration file config.yaml , only one active resourcemanager is configured. Do I need to configure another standby resourcemanager? For hadoop_yarn_resourcemanager_queuemetrics metric, the type in the "Max Capacity" panel is MaxCapacity, but the type in Prometheus is UsedCapacity and AbsoluteUsedCapacity, etc. Metric data with the type of max capacity cannot be found.

**Comment by Mrchumo** [comment]
In the yarn-site.yaml， i configured two resourcemanager, the port of them is both 8088, but i just open the web page of active resourcemanager by port 8088, i can't open the web page of standby resourcemanager. Can I configure another standby resourcemanager?

**Comment by vqcuong** [comment]
hi @Mrchumo, the type "MaxCapacity" is of the metrics hadoop_yarn_resourcemanager_queuemetrics_mb and hadoop_yarn_resourcemanager_queuemetrics_vcores. Can you check it again?
For config multiple resourcemanager on one machine, you can add some configurations below:
`
<property>
  <name>yarn.resourcemanager.ha.enabled</name>
  <value>true</value>
</property>
<property>
  <name>yarn.resourcemanager.cluster-id</name>
  <value>cluster1</value>
</property>
<property>
  <name>yarn.resourcemanager.ha.rm-ids</name>
  <value>rm1,rm2</value>
</property>
<property>
  <name>yarn.resourcemanager.hostname.rm1</name>
  <value>localhost</value>
</property>
<property>
  <name>yarn.resourcemanager.hostname.rm2</name>
  <value>localhost</value>
</property>
<property>
  <name>yarn.resourcemanager.webapp.address.rm1</name>
  <value>localhost:8088</value>
</property>
<property>
  <name>yarn.resourcemanager.webapp.address.rm2</name>
  <value>localhost:8089</value>
</property>
<property>
  <name>hadoop.zk.address</name>
  <value>localhost:2181</value>
</property>
`

**Comment by vqcuong** [comment]
you can refer this doc to more details: https://hadoop.apache.org/docs/stable/hadoop-yarn/hadoop-yarn-site/ResourceManagerHA.html

**Comment by Mrchumo** [comment]
![B44A884C-3D1F-487D-B854-4108B8DDEBCB_1_102_o](https://user-images.githubusercontent.com/40227947/209892719-8e5de3fe-f33f-4eee-9555-06c9c426a978.jpeg)
![1672278019722](https://user-images.githubusercontent.com/40227947/209892756-dc75d9d4-5c3b-4c2d-95ec-4b743bceddef.jpg)
In the first picture, the type of the metric is MaxCapacity, but in the second picture, the data of metric(type is MaxCapacity)  is not found.

**Comment by vqcuong** [comment]
Hi @Mrchumo, sorry for this confusion. I've just checked JMX and realized that there is no type MaxCapacity in Hadoop:service=ResourceManager,name=QueueMetrics beans in version 3.1.3, so the exporter cann't parse and expose it. Can you use the metrics hadoop_yarn_resourcemanager_queuemetrics_mb and hadoop_yarn_resourcemanager_queuemetrics_vcores instead, it's still have MaxCapacity type?

**Comment by Mrchumo** [comment]
i can't change the version of hadoop, let me modify the dashboard, thanks.

**Comment by vqcuong** [comment]
Yeah, Based on version of hadoop, some metric types may be missed. This dashboard I delivered is compatible with version 3.3.x so other versions may be have some metrics without data.
